-- 1. Tabla Usuario
CREATE TABLE Usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    dni VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    telefono VARCHAR(20),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uk_username UNIQUE (username),
    CONSTRAINT uk_dni UNIQUE (dni),
    CONSTRAINT uk_email UNIQUE (email)
);

-- 2. Tabla Cuenta
CREATE TABLE Cuenta (
    id_cuenta BIGINT GENERATED BY DEFAULT AS IDENTITY,
    numero_cuenta VARCHAR(20) NOT NULL,
    usuario_id BIGINT NOT NULL,
    saldo DECIMAL(20, 2) NOT NULL DEFAULT 0.00,
    
    CONSTRAINT pk_cuenta PRIMARY KEY (id_cuenta),
    CONSTRAINT uk_numero_cuenta UNIQUE (numero_cuenta),
    CONSTRAINT check_saldo_positivo CHECK (saldo >= 0),
    
    CONSTRAINT fk_cuenta_usuario 
        FOREIGN KEY (usuario_id) 
        REFERENCES Usuario(id_usuario) 
        ON DELETE CASCADE
);

-- 3. Tabla Transaccion
CREATE TABLE Transaccion (
    id_transaccion BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo VARCHAR(50) NOT NULL,          -- 'INGRESO' o 'RETIRO'
    concepto VARCHAR(255),
    cantidad DECIMAL(20, 2) NOT NULL,
    fecha TIMESTAMP NOT NULL,            
    categoria VARCHAR(50),
    cuenta_id BIGINT NOT NULL,           
    cuenta2_id BIGINT,                      -- Para transferencias, puede ser NULL para ingresos/retiros
    CONSTRAINT pk_transaccion PRIMARY KEY (id_transaccion),
    
    CONSTRAINT chk_tipo_y_cantidad CHECK (
        (tipo = 'INGRESO' AND cantidad > 0) OR 
        (tipo = 'RETIRO' AND cantidad < 0)
    ),
    
    CONSTRAINT fk_transaccion_cuenta 
        FOREIGN KEY (cuenta_id) 
        REFERENCES Cuenta(id_cuenta) 
        ON DELETE CASCADE,
    
    CONSTRAINT fk_transaccion_cuentadestino
        FOREIGN KEY (cuenta2_id) 
        REFERENCES Cuenta(id_cuenta) 
        ON DELETE SET NULL
);